title: Hello World!
author: HRJ
email: huangruijiu@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I like Github so I learn how to use it everyday and I believe that I can become a hit someday!

# social links
twitter_username: HRJ
github_username:  1170300812

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
